----------ROLES Y PERMISOS---------

-----------COMANDOS SEGURIDAD BASE DE DATOS----------------

-----------CREO EL LOGIN-----------------
USE MASTER 
CREATE LOGIN [CONSERVAUDB] WITH PASSWORD='PROYECTO2024', DEFAULT_DATABASE=[MASTER], DEFAULT_LANGUAGE=[ENGLISH], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON

-----------CREO LOS ROLES-----------------
USE  IF5100_2024_CONSERVAU
CREATE ROLE ADMINISTRADOR;  
CREATE ROLE PERSONAL_ADMINISTRATIVO; 
CREATE ROLE PERSONAL_VOLUNTARIO; 

-----------ASIGNO LOS PERMISOS A ROLES-----------------

-------ADMINISTRADOR---------

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ACTIVIDADES_DESAFIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ACTIVO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_BITACORA TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_CARGO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_CLASIFICACION_VOLUNTARIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_DESAFIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_FUNCIONARIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_FUNCIONARIO_CARGO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO_ACTIVO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_PERSONA TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_RECURSO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ROL TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_TIPO_VOLUNTARIO TO ADMINISTRADOR;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_VOLUNTARIO TO ADMINISTRADOR;


-------PERSONAL ADMINISTRATIVO---------

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ACTIVIDADES_DESAFIO TO PERSONAL_ADMINISTRATIVO;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ACTIVO TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT ON TB_BITACORA TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_BITACORA TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT ON TB_CARGO TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_BITACORA TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_CLASIFICACION_VOLUNTARIO TO PERSONAL_ADMINISTRATIVO;

GRANT ON TB_DESAFIO TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_DESAFIO TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT ON TB_FUNCIONARIO TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_FUNCIONARIO TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_FUNCIONARIO_CARGO TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_FUNCIONARIO_CARGO TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO TO PERSONAL_ADMINISTRATIVO;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO_ACTIVO TO PERSONAL_ADMINISTRATIVO;

DENY SELECT, INSERT, DELETE, UPDATE ON TB_PERSONA TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, UPDATE ON TB_RECURSO TO PERSONAL_ADMINISTRATIVO;
DENY DELETE ON TB_RECURSO TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_ROL TO PERSONAL_ADMINISTRATIVO;
DENY INSERT, DELETE, UPDATE ON TB_ROL TO PERSONAL_ADMINISTRATIVO;

GRANT SELECT, INSERT, DELETE, UPDATE ON TB_TIPO_VOLUNTARIO TO PERSONAL_ADMINISTRATIVO;
GRANT SELECT, INSERT, DELETE, UPDATE ON TB_VOLUNTARIO TO PERSONAL_ADMINISTRATIVO;

-------PERSONAL VOLUNTARIO---------

DENY SELECT, INSERT, DELETE, UPDATE ON TB_ACTIVIDADES_DESAFIO TO PERSONAL_VOLUNTARIO;

GRANT SELECT ON TB_ACTIVO TO PERSONAL_VOLUNTARIO;
DENY INSERT, DELETE, UPDATE ON TB_ACTIVO TO PERSONAL_VOLUNTARIO;

DENY SELECT, INSERT, DELETE, UPDATE ON TB_BITACORA TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_CARGO TO PERSONAL_VOLUNTARIO;

GRANT SELECT ON TB_CLASIFICACION_VOLUNTARIO TO PERSONAL_VOLUNTARIO;
DENY INSERT, DELETE, UPDATE ON TB_CLASIFICACION_VOLUNTARIO TO PERSONAL_VOLUNTARIO;

DENY SELECT, INSERT, DELETE, UPDATE ON TB_DESAFIO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_FUNCIONARIO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_FUNCIONARIO_CARGO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_INVENTARIO_ACTIVO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_PERSONA TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_RECURSO TO PERSONAL_VOLUNTARIO;
DENY SELECT, INSERT, DELETE, UPDATE ON TB_ROL TO PERSONAL_VOLUNTARIO;

GRANT SELECT ON TB_TIPO_VOLUNTARIO TO PERSONAL_VOLUNTARIO;
DENY INSERT, DELETE, UPDATE ON TB_TIPO_VOLUNTARIO TO PERSONAL_VOLUNTARIO;

GRANT SELECT, INSERT ON TB_VOLUNTARIO TO PERSONAL_VOLUNTARIO;
DENY DELETE, UPDATE ON TB_VOLUNTARIO TO PERSONAL_VOLUNTARIO;





------------------------ BACKUPS ------------------------

-------- FULL BACKUP --------

USE IF5100_2024_CONSERVAU;
GO

BACKUP DATABASE IF5100_2024_CONSERVAU
	TO DISK = 'C:\tmp\IF5100_2024_CONSERVAU_FULL.bak' 
		WITH INIT,
		NAME = 'FULL BACKUP OF IF5100_2024_CONSERVAU'
GO

-------- BACKUP DIFERENCIAL --------

USE IF5100_2024_CONSERVAU;
GO

BACKUP DATABASE IF5100_2024_CONSERVAU
TO DISK = 'C:\tmp\IF5100_2024_CONSERVAU_Diff.bak' 
WITH DIFFERENTIAL,
     NAME = 'Differential Backup of IF5100_2024_CONSERVAU';
GO

---------- RESTAURACION FULL ----------


USE master;
GO

DECLARE @RutaBackup AS VARCHAR(100);
SET @RutaBackup = 'C:\tmp\IF5100_2024_CONSERVAU_FULL.bak'; -- Ruta del archivo de respaldo completo

RESTORE DATABASE IF5100_2024_CONSERVAU
FROM DISK = @RutaBackup
WITH REPLACE;
GO


---------- RESTAURACION DIFERENCIAL ----------

USE master;
GO

DECLARE @RutaBackup AS VARCHAR(100);
SET @RutaBackup = 'C:\tmp\IF5100_2024_CONSERVAU_Diff.bak'; -- Ruta del archivo de respaldo diferencial

RESTORE DATABASE IF5100_2024_CONSERVAU
FROM DISK = @RutaBackup
WITH NORECOVERY;
GO



